---
  - name: Add in inventory file
    become: true
    lineinfile:
      path: /etc/ansible/hosts
      insertafter: '^[Launched]'
      line: "{{ user }}@{{ item.private_ip }}"
    with_items: "{{ec2.instances }}"

