---
  - hosts: Launched
    become: true
    gather_facts: true
    
    tasks:
    - name: Install Apache
      yum: name=httpd state=present update_cache=yes

    - name: ensure apache is running
      service: name=httpd state=started enabled=yes

