---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
     - name: Delete the object of S3 bucket.
       aws_s3:
         bucket: ansiautocreate
         object: upload-ssh.yml
         mode: delobj        
