---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
     - name: Download the object to local folder from S3 bucket.
       aws_s3:
         bucket: ansiautocreate
         object: s3_object_name
         dest: /folder/path
         mode: get
