---

  - name: Launch the new EC2 Instance
    local_action: ec2
                  group={{ security_group }}
                  instance_type={{ instance_type }}
                  image={{ image }}
                  wait=true
                  region={{ region }}
                  keypair={{ keypair }}
                  count={{ count }}
    register: ec2

  - name: Wait for EC2 Instance to Spin-up and ready for SSH access
    local_action: wait_for
                  host={{ item.public_ip }}
                  port=22
                  delay=60 
                  timeout=320
                  state=started
    with_items: "{{ ec2.instances }}"
