---
  - name: Create New security group with below given name
    local_action:
      module: ec2_group
      name: "{{ security_group }}"
      description: Security Group for Newly Created EC2 Instance
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 114.143.218.74/32
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 18.140.195.89/32
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
