---

  - name: Adding Tag to identity
    local_action: ec2_tag
                  resource={{ item.id }}
                  region={{ region }}
                  state=present
    with_items: "{{ ec2.instances }}"
    args:
      tags:
        Name: "{{ Name }}"
        Owner: "{{ Owner }}"
        Environment: "{{ Env }}"
